[project]
name = "my-casa-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "casatasks>=6.6.5.31",
    "casatools>=6.6.5.31",
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "scipy>=1.15.1",
]
